import type { Field } from 'payload'

/**
 * Moments for single-type listicles. Unlike itinerary moments (one badge per
 * stop), these group places: neighbouring items that share a moment sit under
 * one heading on the reader page, and the list stays numbered 1..N.
 *
 * One catalogue covers every listicle type; the studio editor shows each type
 * its own subset. Append new values at the end -- each one is a Postgres enum
 * value and needs a migration. The website and the studio keep their own copy
 * of this list (labels + icons); keep all three in step.
 */
export const LISTICLE_MOMENT_OPTIONS = [
  // Shared across types
  { label: 'With a view', value: 'with-a-view' },
  { label: 'Rooftops', value: 'rooftop' },
  { label: 'By the water', value: 'by-the-water' },
  { label: 'On a budget', value: 'on-a-budget' },
  { label: 'Worth the splurge', value: 'splurge' },
  { label: 'Date night', value: 'date-night' },
  { label: 'Local favorites', value: 'local-favorite' },
  { label: 'Hidden gems', value: 'hidden-gem' },
  { label: 'Family-friendly', value: 'family-friendly' },
  { label: 'Big groups', value: 'big-groups' },
  { label: 'Wellness & spas', value: 'wellness' },
  { label: 'Shows & performances', value: 'shows' },
  // Dining
  { label: 'Fine dining', value: 'fine-dining' },
  { label: 'Special occasion', value: 'special-occasion' },
  { label: 'Tasting menus', value: 'tasting-menu' },
  { label: 'Chef-driven', value: 'chef-driven' },
  { label: 'Old-school classics', value: 'old-school-classic' },
  { label: 'New & buzzy', value: 'new-and-buzzy' },
  { label: 'Quick lunch', value: 'quick-lunch' },
  { label: 'Street food', value: 'street-food' },
  { label: 'Markets & food halls', value: 'markets-food-halls' },
  { label: 'Casual & laid-back', value: 'casual' },
  { label: 'Breakfast', value: 'breakfast' },
  { label: 'Brunch', value: 'brunch' },
  { label: 'Coffee & cafés', value: 'coffee' },
  { label: 'Bakeries', value: 'bakeries' },
  { label: 'Sweets & desserts', value: 'sweets' },
  { label: 'Seafood', value: 'seafood' },
  { label: 'Grill & meat', value: 'grill' },
  { label: 'Pizza', value: 'pizza' },
  { label: 'Noodles & soups', value: 'noodles-soups' },
  { label: 'Plant-based', value: 'plant-based' },
  { label: 'Healthy & fresh', value: 'healthy' },
  { label: 'Outdoor seating', value: 'outdoor-seating' },
  { label: 'Late-night eats', value: 'late-night-eats' },
  { label: 'Laptop-friendly', value: 'laptop-friendly' },
  { label: 'Wine lovers', value: 'wine-lovers' },
  // Nightlife
  { label: 'Big, loud venues', value: 'big-loud-venues' },
  { label: 'Live bands', value: 'live-bands' },
  { label: 'Live music', value: 'live-music' },
  { label: 'House & techno', value: 'house-techno' },
  { label: 'DJ sets', value: 'dj-sets' },
  { label: 'Salsa & Latin', value: 'latin-nights' },
  { label: 'Jazz & blues', value: 'jazz-blues' },
  { label: 'Karaoke', value: 'karaoke' },
  { label: 'Dance floors', value: 'dance-floors' },
  { label: 'Local hotspots', value: 'local-hotspot' },
  { label: 'Cocktail bars', value: 'cocktail-bars' },
  { label: 'Wine bars', value: 'wine-bars' },
  { label: 'Craft beer', value: 'craft-beer' },
  { label: 'Dive bars', value: 'dive-bars' },
  { label: 'Speakeasies', value: 'speakeasies' },
  { label: 'Chill lounges', value: 'chill-lounges' },
  { label: 'LGBTQ+ friendly', value: 'lgbtq-friendly' },
  { label: 'After hours', value: 'after-hours' },
  { label: 'Early evening', value: 'early-evening' },
  { label: 'Sports bars', value: 'sports-bars' },
  { label: 'Bars with games', value: 'games-bars' },
  // Attractions
  { label: 'Must-see', value: 'must-see' },
  { label: 'Museums', value: 'museums' },
  { label: 'History', value: 'history' },
  { label: 'Art & galleries', value: 'art-galleries' },
  { label: 'Architecture', value: 'architecture' },
  { label: 'Churches & temples', value: 'sacred-sites' },
  { label: 'Parks & gardens', value: 'parks-gardens' },
  { label: 'Nature', value: 'nature' },
  { label: 'Beaches', value: 'beaches' },
  { label: 'Markets', value: 'markets' },
  { label: 'Shopping', value: 'shopping' },
  { label: 'Free to visit', value: 'free' },
  { label: 'Rainy-day picks', value: 'rainy-day' },
  { label: 'Adventure', value: 'adventure' },
  { label: 'On the water', value: 'on-the-water' },
  { label: 'Day trips', value: 'day-trips' },
  { label: 'Tours', value: 'tours' },
  { label: 'Walks', value: 'walks' },
  { label: 'Photo spots', value: 'photo-spots' },
  { label: 'Sunset spots', value: 'sunset-spots' },
  // Accommodations
  { label: 'Luxury', value: 'luxury' },
  { label: 'Boutique', value: 'boutique' },
  { label: 'Design hotels', value: 'design-hotels' },
  { label: 'Historic stays', value: 'historic-stays' },
  { label: 'Good value', value: 'good-value' },
  { label: 'Hostels', value: 'hostels' },
  { label: 'Apartments & rentals', value: 'apartments' },
  { label: 'Romantic', value: 'romantic' },
  { label: 'Beachfront', value: 'beachfront' },
  { label: 'With a pool', value: 'with-a-pool' },
  { label: 'Right in the center', value: 'central' },
  { label: 'Quiet escapes', value: 'quiet-escape' },
  { label: 'Eco stays', value: 'eco-stays' },
  { label: 'Pet-friendly', value: 'pet-friendly' },
  { label: 'Adults only', value: 'adults-only' },
  { label: 'All-inclusive', value: 'all-inclusive' },
  { label: 'Long stays', value: 'long-stays' },
  { label: 'Good for remote work', value: 'remote-work' },
  { label: 'Near the airport', value: 'near-airport' },
  { label: 'Business trips', value: 'business' },
] as const

export const listicleMomentField: Field = {
  name: 'moment',
  label: 'Moment',
  type: 'select',
  enumName: 'listicle_moment',
  options: [...LISTICLE_MOMENT_OPTIONS],
  admin: {
    description:
      'Optional. Places next to each other with the same moment are shown together under one heading.',
  },
}
