#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES: deploy keys for .github/workflows/deploy.yml
#
# One key per job: these two exist only so GitHub can deploy. They are not
# the dashboard's keys, the app's own keys or the setup keys in owner.env, so
# each can be revoked without breaking anything else.
#
# Keys land in ~/.questura-vault/deploy.env (private, never in a repo) and in
# the GitHub "production" environment, which only `main` can use.
# Safe to re-run: Enter keeps what is already saved. Rotating a key = re-run.
#
#   bash apps/questura/scripts/setup-deploy-keys.sh
#
# Procedure it serves: apps/questura/docs/procedures/deploy.md
# ──────────────────────────────────────────────────────────────────────────

REPO=Questurian/questura
GH_ENV=production
VAULT="$HOME/.questura-vault"
ENV_FILE="$VAULT/deploy.env"
RAILWAY_PROJECT_ID=aa5759b2-a793-4f16-8e8b-8633cdc41cac
RAILWAY_ENVIRONMENT_ID=e35f0d85-c66d-4f66-b781-d9e456bab8cb
RAILWAY_TOKEN_QUERY='query { projectToken { projectId environmentId } }'

for tool in gh curl jq; do
  command -v "$tool" >/dev/null || { echo "missing tool: $tool" >&2; exit 2; }
done
gh auth status >/dev/null 2>&1 || { echo "gh is not signed in: run 'gh auth login' first" >&2; exit 2; }
[[ -d "$VAULT" ]] || { echo "no vault at $VAULT" >&2; exit 2; }
touch "$ENV_FILE"; chmod 600 "$ENV_FILE"

# vault_value FILE KEY: one value from a vault file, quotes stripped.
vault_value() { grep -E "^$2=" "$VAULT/$1" 2>/dev/null | tail -n1 | cut -d= -f2- | sed -e 's/^"//' -e 's/"$//'; }

# set_env_secret NAME VALUE: a secret on the GitHub environment (not the repo),
# so a pull request or a fork can never read it.
set_env_secret() {
  if printf '%s' "$2" | gh secret set "$1" --env "$GH_ENV" -R "$REPO" >/dev/null 2>&1; then
    WRITTEN_SECRET+=("$1")
    printf '  %s✓ set%s GitHub secret %s (environment %s)\n' "$GREEN" "$RESET" "$1" "$GH_ENV"
  else
    SKIPPED+=("GitHub secret $1 on environment $GH_ENV")
    warn "could not set $1: re-run this stage"
  fi
}

TOTAL_STAGES=4

banner "Questura deploy keys"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "GitHub: the production environment"
say "A locked box in GitHub for the deploy keys. Only the main branch can open it."
say "This stage does it for you; nothing to click."
if gh api -X PUT "repos/$REPO/environments/$GH_ENV" --input - >/dev/null <<'JSON'
{"deployment_branch_policy": {"protected_branches": false, "custom_branch_policies": true}}
JSON
then
  gh api -X POST "repos/$REPO/environments/$GH_ENV/deployment-branch-policies" \
    -f name=main -f type=branch >/dev/null 2>&1 || true   # already there on a re-run
  printf '  %s✓%s environment "%s" exists, branches allowed: %s\n' "$GREEN" "$RESET" "$GH_ENV" \
    "$(gh api "repos/$REPO/environments/$GH_ENV/deployment-branch-policies" --jq '[.branch_policies[].name] | join(", ")')"
else
  SKIPPED+=("GitHub environment $GH_ENV")
  warn "could not create the environment (do you have admin on $REPO?)"
fi
sleep 1

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "GitHub: the website's public settings"
say "Values baked into the website that every visitor can already see."
say "Copied from the vault, the same ones the live site was built with."
PK=$(vault_value owner.env STRIPE_PUBLISHABLE_KEY)
MAPS=$(vault_value generated.env NEXT_PUBLIC_GOOGLE_MAPS_API_KEY)
END_ON=$(vault_value generated.env NEXT_PUBLIC_ENDORSELY_ENABLED)
END_ORG=$(vault_value generated.env NEXT_PUBLIC_ENDORSELY_ORG_ID)
[[ "$PK" == pk_live_* ]] || { warn "owner.env has no pk_live_ STRIPE_PUBLISHABLE_KEY"; PK=""; }
[[ -n "$PK" ]]   && set_var STRIPE_PUBLISHABLE_KEY "$PK"
[[ -n "$MAPS" ]] && set_var GOOGLE_MAPS_API_KEY "$MAPS"
set_var ENDORSELY_ENABLED "${END_ON:-true}"
[[ -n "$END_ORG" ]] && set_var ENDORSELY_ORG_ID "$END_ORG"
set_var IMAGE_CDN_ORIGIN "https://questurian-cdn.b-cdn.net"
set_env_secret CLOUDFLARE_ACCOUNT_ID "$(vault_value generated.env CLOUDFLARE_ACCOUNT_ID)"
sleep 1

# railway_ok TOKEN: does Railway accept it for questura / production? (read-only)
# The query is built outside $(...): macOS bash 3.2 misparses braces inside it.
railway_ok() {
  local body got
  body=$(jq -nc --arg q "$RAILWAY_TOKEN_QUERY" '{query: $q}')
  got=$(curl -sS --max-time 30 https://backboard.railway.com/graphql/v2 \
    -H "Project-Access-Token: $1" -H 'Content-Type: application/json' \
    --data-binary "$body" 2>/dev/null || true)
  [[ "$(jq -r '.data.projectToken.projectId // empty' <<<"$got" 2>/dev/null)" == "$RAILWAY_PROJECT_ID" ]] &&
  [[ "$(jq -r '.data.projectToken.environmentId // empty' <<<"$got" 2>/dev/null)" == "$RAILWAY_ENVIRONMENT_ID" ]]
}

# cloudflare_ok TOKEN [loud]: can it reach everything a deploy touches? (read-only)
cloudflare_ok() {
  local token=$1 loud=${2:-} ok=0 check path label
  for check in "user/tokens/verify:token is active" \
               "accounts/$CF_ACCOUNT_ID/workers/scripts:Workers" \
               "accounts/$CF_ACCOUNT_ID/r2/buckets:R2 storage" \
               "accounts/$CF_ACCOUNT_ID/d1/database:D1"; do
    path=${check%%:*}; label=${check#*:}
    if [[ "$(curl -sS --max-time 30 -H "Authorization: Bearer $token" \
          "https://api.cloudflare.com/client/v4/$path" 2>/dev/null | jq -r '.success' 2>/dev/null)" == true ]]; then
      [[ -n "$loud" ]] && printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$label"
    else
      [[ -n "$loud" ]] && warn "no access: $label"
      ok=1
    fi
  done
  return $ok
}

# github_has_secret NAME: is it already on the production environment?
github_has_secret() { gh secret list --env "$GH_ENV" -R "$REPO" 2>/dev/null | awk '{print $1}' | grep -qx "$1"; }

# already_done: say so and move on, without opening anything.
already_done() {
  printf '  %s✓ Already done:%s %s\n' "$GREEN" "$RESET" "$1"
  note "Skipping. (To replace it, empty its line in $ENV_FILE and re-run.)"
  sleep 2
}

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Railway: a deploy-only token"
RAILWAY_DEPLOY_TOKEN=$(_existing RAILWAY_DEPLOY_TOKEN || true)
if [[ -n "$RAILWAY_DEPLOY_TOKEN" ]] && railway_ok "$RAILWAY_DEPLOY_TOKEN" && github_has_secret RAILWAY_TOKEN; then
  already_done "saved token works, and GitHub has it."
else
  say "Lets GitHub start a deploy of the API. Scoped to this one project."
  open_url "https://railway.com/project/$RAILWAY_PROJECT_ID/settings/tokens"
  step "You are on Project Settings → Tokens (project 'questura')."
  step "Token name: github-deploy"
  step "Environment: production"
  step "Click Create, then copy the token it shows (it is shown once)."
  note "Not your account token, and not the dashboard's token: a new one."
  while :; do
    ask_secret RAILWAY_DEPLOY_TOKEN "Paste the Railway token:"
    [[ -n "$RAILWAY_DEPLOY_TOKEN" ]] || { warn "empty; paste the token"; continue; }
    if railway_ok "$RAILWAY_DEPLOY_TOKEN"; then
      printf '  %s✓%s token works for project questura, environment production\n' "$GREEN" "$RESET"
      break
    fi
    warn "Railway did not accept it for questura / production."
    note "Check it was made under this project with Environment = production, then paste again."
    RAILWAY_DEPLOY_TOKEN=""; write_env RAILWAY_DEPLOY_TOKEN ""
  done
  write_env RAILWAY_DEPLOY_TOKEN "$RAILWAY_DEPLOY_TOKEN"
  set_env_secret RAILWAY_TOKEN "$RAILWAY_DEPLOY_TOKEN"
  pause "Press Enter for the next stage"
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare: a deploy-only token"
CF_ACCOUNT_ID=$(vault_value generated.env CLOUDFLARE_ACCOUNT_ID)
CLOUDFLARE_DEPLOY_TOKEN=$(_existing CLOUDFLARE_DEPLOY_TOKEN || true)
if [[ -n "$CLOUDFLARE_DEPLOY_TOKEN" ]] && cloudflare_ok "$CLOUDFLARE_DEPLOY_TOKEN" && github_has_secret CLOUDFLARE_API_TOKEN; then
  already_done "saved token works, and GitHub has it."
else
  say "Lets GitHub upload the website. Nothing else."
  open_url "https://dash.cloudflare.com/profile/api-tokens"
  step "Click 'Create Token', scroll down, 'Create Custom Token' → Get started."
  step "Token name: github-deploy"
  step "Permissions: 3 rows (use '+ Add more' for rows 2 and 3):"
  say  "     Account | Workers Scripts    | Edit"
  say  "     Account | Workers R2 Storage | Edit"
  say  "     Account | D1                 | Edit"
  step "Account Resources: Include | (your account)"
  note "No Zone rows and no Zone Resources: the deploy never touches the domain."
  step "Leave the rest. 'Continue to summary' → 'Create Token' → copy it (shown once)."
  while :; do
    ask_secret CLOUDFLARE_DEPLOY_TOKEN "Paste the Cloudflare token:"
    [[ -n "$CLOUDFLARE_DEPLOY_TOKEN" ]] || { warn "empty; paste the token"; continue; }
    cloudflare_ok "$CLOUDFLARE_DEPLOY_TOKEN" loud && break
    note "Edit the token in Cloudflare (… → Edit) to add what is missing, then paste it again."
    CLOUDFLARE_DEPLOY_TOKEN=""; write_env CLOUDFLARE_DEPLOY_TOKEN ""
  done
  write_env CLOUDFLARE_DEPLOY_TOKEN "$CLOUDFLARE_DEPLOY_TOKEN"
  set_env_secret CLOUDFLARE_API_TOKEN "$CLOUDFLARE_DEPLOY_TOKEN"
fi

finish
say "Next: merge the PR. Watch it go live at https://github.com/$REPO/actions/workflows/deploy.yml"
say "To rotate a key later: delete it in Railway/Cloudflare, re-run this script."
printf '\n'
